# Generated by Django 5.2.7 on 2026-09-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TVSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Series Synopsis')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='tv/posters/', verbose_name='Poster Image')),
                ('poster_url', models.CharField(blank=True, max_length=500, verbose_name='External Poster URL')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='tv/backdrops/', verbose_name='Backdrop Image')),
                ('backdrop_url', models.CharField(blank=True, max_length=500, verbose_name='External Backdrop URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tv/thumbnails/', verbose_name='Thumbnail')),
                ('trailer_url', models.URLField(blank=True, max_length=500, verbose_name='Trailer URL')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('release_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Release Year')),
                ('age_rating', models.CharField(default='TV-MA', max_length=20, verbose_name='Age Rating')),
                ('imdb_rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='IMDb Rating')),
                ('tmdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='TMDB Rating')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Total Views')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured')),
                ('trending', models.BooleanField(db_index=True, default=False, verbose_name='Trending')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('category', models.CharField(choices=[('tv_series', 'TV Series'), ('web_series', 'Web Series'), ('anime', 'Anime'), ('kids', 'Kids'), ('documentary', 'Documentary Series')], db_index=True, default='tv_series', max_length=50, verbose_name='Category')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cast', models.ManyToManyField(blank=True, related_name='tv_series_cast', to='movies.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='tv_series_directors', to='movies.person')),
                ('genres', models.ManyToManyField(blank=True, related_name='tv_series', to='genres.genre')),
            ],
            options={
                'verbose_name': 'TV Series',
                'verbose_name_plural': 'TV Series',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveIntegerField(verbose_name='Season Number')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='Season Title')),
                ('description', models.TextField(blank=True, verbose_name='Season Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='tv/seasons/', verbose_name='Season Poster')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='tv.tvseries')),
            ],
            options={
                'verbose_name': 'Season',
                'verbose_name_plural': 'Seasons',
                'ordering': ['season_number'],
                'unique_together': {('series', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveIntegerField(verbose_name='Episode Number')),
                ('title', models.CharField(max_length=255, verbose_name='Episode Title')),
                ('description', models.TextField(blank=True, verbose_name='Episode Description')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='tv/episodes/', verbose_name='Thumbnail')),
                ('thumbnail_url', models.CharField(blank=True, max_length=500, verbose_name='External Thumbnail URL')),
                ('duration', models.CharField(blank=True, help_text='e.g. 52m', max_length=50, verbose_name='Duration Label')),
                ('duration_minutes', models.PositiveIntegerField(default=45, verbose_name='Duration (Minutes)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Air Date')),
                ('video', models.FileField(blank=True, null=True, upload_to='tv/videos/', verbose_name='Video File')),
                ('video_url', models.URLField(blank=True, max_length=500, verbose_name='External Video Stream URL')),
                ('trailer_url', models.URLField(blank=True, max_length=500, verbose_name='Episode Preview / Trailer')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Views')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='tv.season')),
            ],
            options={
                'verbose_name': 'Episode',
                'verbose_name_plural': 'Episodes',
                'ordering': ['episode_number'],
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
