# Generated by Django 5.2.7 on 2026-09-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=255, verbose_name='Movie Name')),
                ('release_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Release Year')),
                ('genre', models.CharField(blank=True, max_length=100, verbose_name='Genre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='submissions/posters/', verbose_name='Poster Upload')),
                ('email', models.EmailField(max_length=254, verbose_name='Submitter Email')),
                ('agree_terms', models.BooleanField(default=True, verbose_name='Agreed to Terms')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=30, verbose_name='Review Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Movie Submission',
                'verbose_name_plural': 'User Movie Submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='Full Name')),
                ('role', models.CharField(choices=[('actor', 'Actor'), ('director', 'Director'), ('writer', 'Writer'), ('producer', 'Producer')], default='actor', max_length=50, verbose_name='Primary Role')),
                ('bio', models.TextField(blank=True, verbose_name='Biography')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='movies/people/', verbose_name='Photo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Person (Cast & Crew)',
                'verbose_name_plural': 'People (Cast & Crew)',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=280, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Plot Summary')),
                ('poster', models.ImageField(blank=True, null=True, upload_to='movies/posters/', verbose_name='Poster Image')),
                ('poster_url', models.CharField(blank=True, help_text='Used when hosting external poster images', max_length=500, verbose_name='External Poster URL')),
                ('backdrop', models.ImageField(blank=True, null=True, upload_to='movies/backdrops/', verbose_name='Backdrop Image')),
                ('backdrop_url', models.CharField(blank=True, max_length=500, verbose_name='External Backdrop URL')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='movies/thumbnails/', verbose_name='Thumbnail')),
                ('trailer_url', models.URLField(blank=True, max_length=500, verbose_name='Trailer URL (YouTube/MP4)')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('release_year', models.PositiveIntegerField(blank=True, db_index=True, null=True, verbose_name='Release Year')),
                ('duration', models.CharField(blank=True, help_text='e.g. 2h 42m', max_length=50, verbose_name='Duration Label')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Duration (Minutes)')),
                ('language', models.CharField(default='English', max_length=50, verbose_name='Audio Language')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='Country of Origin')),
                ('age_rating', models.CharField(default='PG-13', max_length=20, verbose_name='Age Rating')),
                ('content_rating', models.CharField(blank=True, max_length=50, verbose_name='Content Rating')),
                ('status', models.CharField(choices=[('released', 'Released'), ('upcoming', 'Upcoming'), ('in_production', 'In Production')], default='released', max_length=30, verbose_name='Status')),
                ('imdb_rating', models.DecimalField(db_index=True, decimal_places=1, default=0.0, max_digits=3, verbose_name='IMDb Rating')),
                ('tmdb_rating', models.DecimalField(decimal_places=1, default=0.0, max_digits=3, verbose_name='TMDB Rating')),
                ('views', models.PositiveBigIntegerField(default=0, verbose_name='Total Views')),
                ('featured', models.BooleanField(db_index=True, default=False, verbose_name='Featured on Hero Carousel')),
                ('trending', models.BooleanField(db_index=True, default=False, verbose_name='Trending Now')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active / Published')),
                ('category', models.CharField(choices=[('hollywood', 'Hollywood'), ('bollywood', 'Bollywood'), ('kids', 'Kids'), ('web_series', 'Web Series'), ('anime', 'Anime'), ('popular', 'Popular'), ('other', 'Other')], db_index=True, default='hollywood', max_length=50, verbose_name='Category')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated keywords', max_length=500, verbose_name='Tags')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('genres', models.ManyToManyField(blank=True, related_name='movies', to='genres.genre')),
            ],
            options={
                'verbose_name': 'Movie',
                'verbose_name_plural': 'Movies',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character_name', models.CharField(blank=True, max_length=255, verbose_name='Character / Role Name')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_cast', to='movies.movie')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_roles', to='movies.person')),
            ],
            options={
                'verbose_name': 'Movie Cast Member',
                'verbose_name_plural': 'Movie Cast Members',
                'ordering': ['order'],
                'unique_together': {('movie', 'person')},
            },
        ),
        migrations.AddField(
            model_name='movie',
            name='cast',
            field=models.ManyToManyField(blank=True, related_name='acted_movies', through='movies.MovieCast', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ManyToManyField(blank=True, related_name='directed_movies', to='movies.person'),
        ),
        migrations.AddField(
            model_name='movie',
            name='writers',
            field=models.ManyToManyField(blank=True, related_name='written_movies', to='movies.person'),
        ),
    ]
