# Generated by Django 5.2.7 on 2026-09-23 20:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('tv', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='en', help_text='e.g. en, bn, hi, es', max_length=10, verbose_name='Language Code')),
                ('label', models.CharField(default='English', help_text='e.g. English, Bengali, Hindi', max_length=50, verbose_name='Language Label')),
                ('subtitle_file', models.FileField(upload_to='streaming/subtitles/', verbose_name='Subtitle File (.vtt or .srt)')),
                ('is_default', models.BooleanField(default=False, verbose_name='Default Subtitle')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_subtitles', to='tv.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subtitles', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Subtitle',
                'verbose_name_plural': 'Subtitles',
                'ordering': ['language'],
            },
        ),
        migrations.CreateModel(
            name='VideoSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality', models.CharField(choices=[('360p', '360p (SD)'), ('480p', '480p (SD)'), ('720p', '720p (HD)'), ('1080p', '1080p (Full HD)'), ('4k', '4K (Ultra HD)')], default='720p', max_length=20, verbose_name='Video Quality')),
                ('file', models.FileField(blank=True, null=True, upload_to='streaming/videos/', verbose_name='Video File')),
                ('source_url', models.URLField(blank=True, max_length=1000, verbose_name='External Video Stream URL / CDN')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode_video_sources', to='tv.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='video_sources', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Video Source',
                'verbose_name_plural': 'Video Sources',
                'ordering': ['quality'],
            },
        ),
    ]
