# Generated by Django 5.2.7 on 2026-09-23 20:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0001_initial'),
        ('tv', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_position', models.FloatField(default=0.0, verbose_name='Current Position (seconds)')),
                ('duration', models.FloatField(default=1.0, verbose_name='Total Duration (seconds)')),
                ('completed', models.BooleanField(default=False, verbose_name='Watched to End')),
                ('last_watched', models.DateTimeField(auto_now=True, verbose_name='Last Watched')),
                ('episode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='tv.episode')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='movies.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Watch History',
                'verbose_name_plural': 'Watch History',
                'ordering': ['-last_watched'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('movie__isnull', False)), fields=('user', 'movie'), name='unique_user_movie_history'), models.UniqueConstraint(condition=models.Q(('episode__isnull', False)), fields=('user', 'episode'), name='unique_user_episode_history')],
            },
        ),
    ]
